[package]
name = "rust-url-shortener"
version = "0.1.0"
edition = "2024"

[dependencies]
mongodb = "2.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
rand = { version = "0.8", features = ["std_rng"] }
futures = "0.3.31"
